consul:
  ports:
  - 8500:8500/tcp
  domainname: service.consul
  labels:
    io.rancher.container.pull_image: always
  command:
  - -server
  - -bootstrap
  hostname: consul
  image: sequenceiq/consul:v0.5.0-v6
